
#ifndef _OASM_H_
#define _OASM_H_

#define WCHAR_＾            ((wchar_t)0xFF3E)//＾
#define WCHAR_Ω            ((wchar_t)0x03A9)//Ω
#define WCHAR_ω            ((wchar_t)0x03C9)//ω
#define WCHAR_∞            ((wchar_t)0x221E)//∞
#define WCHAR_∽            ((wchar_t)0x223D)//∽
#define WCHAR_≌            ((wchar_t)0x224C)//≌
#define WCHAR_Φ            ((wchar_t)0x03A6)//Φ
#define WCHAR_φ            ((wchar_t)0x03C6)//φ
#define WCHAR_↘            ((wchar_t)0x2198)//↘
#define WCHAR_↖            ((wchar_t)0x2196)//↖
#define WCHAR_↑            ((wchar_t)0x2191)//↑
#define WCHAR_↓            ((wchar_t)0x2193)//↓
#define WCHAR_→            ((wchar_t)0x2192)//→
#define WCHAR_←            ((wchar_t)0x2190)//←
#define WCHAR_↙            ((wchar_t)0x2199)//↙
#define WCHAR_↗            ((wchar_t)0x2197)//↗
#define WCHAR_≮            ((wchar_t)0x226E)//≮
#define WCHAR_≯            ((wchar_t)0x226F)//≯
#define WCHAR_§            ((wchar_t)0x00A7)//§
#define WCHAR_∠            ((wchar_t)0x2220)//∠
#define WCHAR_∨            ((wchar_t)0x2228)//∨
#define WCHAR_∧            ((wchar_t)0x2227)//∧
#define WCHAR_≥            ((wchar_t)0x2265)//≥
#define WCHAR_≤            ((wchar_t)0x2264)//≤
#define WCHAR_×            ((wchar_t)0x00D7)//×
#define WCHAR_÷            ((wchar_t)0x00F7)//÷
#define WCHAR_♂            ((wchar_t)0x2642)//♂
#define WCHAR_♀            ((wchar_t)0x2640)//♀
#define WCHAR_◎            ((wchar_t)0x25CE)//◎
#define WCHAR_≈            ((wchar_t)0x2248)//≈
#define WCHAR_√            ((wchar_t)0x221A)//√
#define WCHAR_±            ((wchar_t)0x00B1)//±
#define WCHAR_∫            ((wchar_t)0x222B)//函数
#define WCHAR_∮            ((wchar_t)0x222E)//如果
#define WCHAR_∝            ((wchar_t)0x221D)//否则
#define WCHAR_‖            ((wchar_t)0x2016)//或者/暂停
#define WCHAR_∪            ((wchar_t)0x222A)//并且
#define WCHAR_∏            ((wchar_t)0x220F)//开始
#define WCHAR_∈            ((wchar_t)0x2208)//类型定义
#define WCHAR_°            ((wchar_t)0x00B0)//内存分配粒度
#define WCHAR_′            ((wchar_t)0x2032)//进制修饰符
#define WCHAR_﹉            ((wchar_t)0xFE49)//连接符
#define WCHAR_﹍            ((wchar_t)0xFE4D)
#define WCHAR_…            ((wchar_t)0x2026)
#define WCHAR_︵            ((wchar_t)0xFE35)//段
#define WCHAR_︶            ((wchar_t)0xFE36)
#define WCHAR_︻            ((wchar_t)0xFE3B)//数据段
#define WCHAR_︼            ((wchar_t)0xFE3C)
#define WCHAR_﹃            ((wchar_t)0xFE43)//只读段
#define WCHAR_﹄            ((wchar_t)0xFE44)
#define WCHAR_﹁            ((wchar_t)0xFE41)//预留段
#define WCHAR_﹂            ((wchar_t)0xFE42)
#define WCHAR_︹            ((wchar_t)0xFE39)//附加段
#define WCHAR_︺            ((wchar_t)0xFE3A) 
#define WCHAR_︿            ((wchar_t)0xFE3F)//堆栈段
#define WCHAR_﹀            ((wchar_t)0xFE40) 
#define WCHAR_︽            ((wchar_t)0xFE3D)//外部引用
#define WCHAR_︾            ((wchar_t)0xFE3E)
#define WCHAR_︷            ((wchar_t)0xFE37)//代码段
#define WCHAR_︸            ((wchar_t)0xFE38)
#define WCHAR_「            ((wchar_t)0x300C)//块注释
#define WCHAR_」            ((wchar_t)0x300D)
#define WCHAR_∥            ((wchar_t)0x2225)//行注释
#define WCHAR_ˇ            ((wchar_t)0x02C7)//联接符
#define WCHAR_ˉ            ((wchar_t)0x02C9)//求补
#define WCHAR_π            ((wchar_t)0x03C0)//π
#define WCHAR_㏒            ((wchar_t)0x33D2)//㏒
#define WCHAR_㏑            ((wchar_t)0x33D1)//ln
#define WCHAR_∑            ((wchar_t)0x2211)//结构体
#define WCHAR_σ            ((wchar_t)0x03C3)//联合体
#define WCHAR_ξ            ((wchar_t)0x03BE)//枚举
#define WCHAR_∵            ((wchar_t)0x2235)//定义
#define WCHAR_《            ((wchar_t)0x300A)//引用文开始符
#define WCHAR_》            ((wchar_t)0x300B)//引用文结束符
#define WCHAR_〈            ((wchar_t)0x3008)//引用库开始符
#define WCHAR_〉            ((wchar_t)0x3009)//引用库结束符
#define WCHAR_【            ((wchar_t)0x3010)//引用码开始符
#define WCHAR_】            ((wchar_t)0x3011)//引用码结束符
#define WCHAR_‥            ((wchar_t)0x2025)//数组定义
#define WCHAR_：            ((wchar_t)0xFF1A)//数组成员引用
#define WCHAR_‘            ((wchar_t)0x2018)//宽单字符开始
#define WCHAR_’            ((wchar_t)0x2019)//宽单字符结束
#define WCHAR_“            ((wchar_t)0x201C)//宽字符串开始
#define WCHAR_”            ((wchar_t)0x201D)//宽字符串结束
#define WCHAR_＆            ((wchar_t)0xFF06)//取全局变量地址
#define WCHAR_～            ((wchar_t)0xFF5E)//标签定义
#define WCHAR_▽            ((wchar_t)0x25BD)//ENTER
#define WCHAR_△            ((wchar_t)0x25B3)//LEAVE

#endif //_OASM_H_