#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDR_MENU_MAIN                           109
#define IDD_OPTION                              118
#define IDB_TOOLBAR                             120
#define IDI_MAIN                                122
#define IDB_TREE                                124
#define IDD_ABOUT                               126
#define IDD_TCP_CHAT                            128
#define IDD_UDP_CHAT                            130
#define IDD_URL_DOWNLOAD                        132
#define IDC_CHECKBOX3                           1000
#define IDC_EDIT_SELF_NICKNAME                  1000
#define IDC_STATIC_INFO                         1000
#define IDC_STATIC_SOCKET                       1000
#define IDC_BUTTON_DOWNLOAD                     1001
#define IDC_BUTTON_LOGIN                        1001
#define IDC_EDIT_URL                            1002
#define IDC_EDIT_SERVER_ADDR                    1005
#define IDC_LIST_MEMBER                         1006
#define IDC_EDIT_UDP_NICKNAME                   1007
#define IDC_EDIT_NICKNAME                       1008
#define IDC_EDIT_UDP_USER_ADDR                  1008
#define IDC_BUTTON_ADDTO_USER_LIST              1009
#define IDC_EDIT_AGE                            1009
#define IDM_NEW                                 40000
#define IDM_OPEN                                40001
#define IDM_QUIT                                40002
#define IDM_UNDO                                40003
#define IDM_REDO                                40004
#define IDM_OPTION                              40005
#define IDM_ABOUT                               40006
#define IDM_SAVE                                40007
#define IDC_TREE1                               40008
#define IDM_SAVEAS                              40008
#define IDC_COMBO1                              40009
#define IDM_ASSOCIATE_WWD                       40009
#define IDM_UNASSOCIATE_WWD                     40010
#define IDC_CHECKBOX1                           40011
#define IDM_STATIC_CALL_DLLFUN                  40011
#define IDC_CHECKBOX2                           40012
#define IDM_DYNAMIC_CALL_DLLFUN                 40012
#define IDC_LIST1                               40013
#define IDM_TCP_CHAT                            40013
#define IDC_PROGRESS1                           40014
#define IDM_UDP_CHAT                            40014
#define IDC_EDIT1                               40015
#define IDM_URL_DOWNLOAD                        40015
#define IDC_BUTTON_ADD                          40016
#define IDC_BUTTON_MODIFY                       40017
#define IDC_BUTTON_DELETE                       40018
#define IDC_BUTTON_FIRST                        40019
#define IDC_BUTTON_NEXT                         40020
#define IDC_BUTTON_LAST                         40021
#define IDC_BUTTON_PREVIOUS                     40022
#define IDC_CHECKBOX_TALKTO                     40023
#define IDC_LIST_TALKTO                         40024
#define IDC_EDIT_SAY                            40025
#define IDC_BUTTON_SEND                         40026
#define IDC_EDIT_CHAT_CONTENT                   40027
#define IDC_LIST_UDP_USER                       40027
#define IDC_EDIT_UDP_CHAT_CONTENT               40029
#define IDC_EDIT_UDP_SAY                        40030
#define IDC_BUTTON_UDP_SEND                     40031
