//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OLIDE.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_CPUWATCH_WND                101
#define IDS_MEM_WATCH_WND               102
#define IDR_POPUP_EDIT                  119
#define IDR_POPUP_OASM_EDIT             119
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_OLIDETYPE                   130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_PROPERTIES                   135
#define ID_OPEN_WITH                    136
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_FILEVIEW                150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_SOLUTION              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_BUILD_CODE                  185
#define IDR_THEME_MENU                  200
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_CUSTOMIZE               219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EDIT_MENU                   303
#define IDS_OASM_EDIT_MENU              303
#define IDS_SOLUTION                    304
#define IDS_PROJECT                     305
#define IDS_FLODER                      306
#define IDS_FILE                        307
#define IDS_OML_EDIT_MENU               308
#define IDR_POPUP_TAB                   310
#define IDD_DLG_SYSTEM_OPTION           312
#define IDD_DLG_OASM_EDIT_OPTION        313
#define IDD_DLG_LINK_OPTION             314
#define IDD_DLG_OASM_OPTION             315
#define IDB_HDRDOWN                     317
#define ID_VIEW_CPUWATCHWND             317
#define IDB_HDRUP                       318
#define ID_VIEW_MEMWATCHWND             318
#define IDI_OPTION_EDITOR               328
#define IDI_OPTION_LINK                 329
#define IDI_OPTION_OASM                 331
#define IDR_SYNTAX_WORD                 352
#define IDR_OPERATOR                    354
#define IDR_BUILD_CODE1                 355
#define IDI_OAM_FILE                    365
#define IDI_OAH_FILE                    366
#define IDB_SOLUTION_TREE               367
#define IDD_DLG_NEW_PROJECT             368
#define IDD_DLG_NEW_SOLUTION            369
#define IDD_DLG_NEW_FILE                370
#define IDD_DLG_NEW_ITEM_MANAGER        371
#define IDB_BITMAP_ADD_NEW_ITEM         372
#define IDR_POPUP_PROJECT               373
#define IDR_POPUP_FLODER                374
#define IDR_POPUP_FILE                  375
#define IDD_DLG_LINK_PROPERTY           376
#define IDR_POPUP_OML_EDIT              377
#define IDI_SOLUTION                    378
#define IDI_FILE                        379
#define IDI_PROJECT                     381
#define IDD_DLG_COMMON_OPTION           382
#define IDI_OPTION_COMMON               383
#define IDD_DLG_DOASM_OPTION            384
#define IDD_CPU_WATCH_WND               385
#define IDD_MEM_WATCH_WND               386
#define IDD_DLG_OML_EDIT_OPTION         387
#define IDI_OMH_FILE                    387
#define IDD_DLG_OML_OPTION              388
#define IDI_ICON2                       388
#define IDI_OMP_FILE                    388
#define IDI_OPR_FILE                    389
#define IDI_OSL_FILE                    390
#define IDR_EDIT_VIEW                   391
#define IDC_EDIT_TEXT                   1000
#define IDC_PROJCET_PROPERTY_ITEM_RECT  1001
#define IDC_LIST1                       1002
#define IDC_LIST_PROJECT                1003
#define IDC_LIST_SOLUTION               1003
#define IDC_LIST_FILE                   1003
#define IDC_TREE_PROP_ADD_ITEM_RECT     1004
#define IDC_EDIT_ITEM_NAME              1005
#define IDC_STATIC_ITEM_NAME            1006
#define IDC_STATIC_ITEM_PATH            1007
#define IDC_BUTTON_GET_PATH             1008
#define IDC_COMBO_ITEM_PATH             1009
#define IDC_EDIT_EBX                    1010
#define IDC_EDIT_EAX                    1011
#define IDC_EDIT_ECX                    1012
#define IDC_EDIT_EDX                    1013
#define IDC_EDIT_EBP                    1014
#define IDC_EDIT_ESP                    1015
#define IDC_EDIT_ESI                    1016
#define IDC_EDIT_EDI                    1017
#define IDC_EDIT_EIP                    1018
#define IDC_EDIT_ST0_MMX0               1019
#define IDC_EDIT_ST1_MMX1               1020
#define IDC_EDIT_ST2_MMX2               1021
#define IDC_EDIT_ST3_MMX3               1022
#define IDC_EDIT_ST4_MMX4               1023
#define IDC_EDIT_ST5_MMX5               1024
#define IDC_EDIT_ST6_MMX6               1025
#define IDC_EDIT_ST7_MMX7               1026
#define IDC_LIST_EFLAG32                1027
#define IDC_EDIT_XMM0                   1028
#define IDC_EDIT_HEX_VIEW_CODE_SEGMENT  1028
#define IDC_EDIT_XMM1                   1029
#define IDC_EDIT_MEM_ADDR               1029
#define IDC_EDIT_XMM2                   1030
#define IDC_EDIT_MEM_LENGTH             1030
#define IDC_EDIT_XMM3                   1031
#define IDC_BUTTON_GET_DATA             1031
#define IDC_EDIT_XMM4                   1032
#define IDC_EDIT_DATA_UCHAR             1032
#define IDC_EDIT_XMM5                   1033
#define IDC_EDIT_DATA_CHAR              1033
#define IDC_EDIT_XMM6                   1034
#define IDC_EDIT_DATA_USHORT            1034
#define IDC_EDIT_XMM7                   1035
#define IDC_EDIT_DATA_SHORT             1035
#define IDC_EDIT_CS                     1036
#define IDC_EDIT_DATA_UINT              1036
#define IDC_EDIT_DS                     1037
#define IDC_EDIT_DATA_INT               1037
#define IDC_EDIT_ES                     1038
#define IDC_EDIT_DATA_ADDR              1038
#define IDC_EDIT_SS                     1039
#define IDC_EDIT_DATA_STRING            1039
#define IDC_EDIT_FS                     1040
#define IDC_EDIT_HEX_VIEW_CODE_SEGMENT2 1040
#define IDC_EDIT_HEX_VIEW_DATA_SEGMENT  1040
#define IDC_EDIT_GS                     1041
#define IDC_EDIT_HEX_VIEW_CODE_SEGMENT3 1041
#define IDC_EDIT_HEX_VIEW_STACK_SEGMENT 1041
#define IDC_BTN_SAVE_CODE_SEGMENT       1042
#define IDC_BTN_SAVE_DATA_SEGMENT       1043
#define IDC_BTN_SAVE_STACK_SEGMENT      1044
#define IDC_EDIT_CODE_DOASM             1045
#define IDC_BTN_CODE_DOASM              1046
#define IDC_BTN_GET_DATA_SEGMENT        1047
#define IDC_CHECK_SHOW_DS_VIEW_ONLY     1048
#define IDC_STATIC_CS                   1049
#define IDC_STATIC_CS_DOASM             1050
#define IDC_STATIC_SS                   1051
#define IDC_STATIC_DS                   1052
#define IDC_EDIT_READ_CODE_LENGTH       1053
#define ID_CLOSE_CUR_CHILD_FRAME        32773
#define ID_CLOSE_ALL_CHILD_FRAME        32774
#define ID_OPEN_OWNER_FLODER            32777
#define ID_BUILD_PROJECT                32780
#define ID_BUILD_ALL                    32781
#define ID_LINK_PROJECT                 32782
#define ID_BUILD_AND_LINK               32783
#define ID_BUILD_AND_RUN                32784
#define ID_DUMMY_SELECT_ACTIVE_CONFIGURATION 32785
#define ID_SYSTEM_OPTIONS               32786
#define ID_SYNTAX_WORD_COMMENT_LINE     32812
#define ID_SYNTAX_WORD_COMMENT_BLOCK    32813
#define ID_SYNTAX_WORD_INCLUDE_TEXT     32815
#define ID_SYNTAX_WORD_INCLUDE_LIB      32816
#define ID_SYNTAX_WORD_SEGMENT_DATA     32817
#define ID_SYNTAX_WORD_SEGMENT_RDATA    32818
#define ID_SYNTAX_WORD_SEGMENT_BSS      32819
#define ID_SYNTAX_WORD_SEGMENT_CODE     32824
#define ID_SYNTAX_WORD_STRUCT           32825
#define ID_SYNTAX_WORD_UNION            32826
#define ID_SYNTAX_WORD_ENUM             32827
#define ID_SYNTAX_WORD_TYPE_DEFINE      32828
#define ID_SYNTAX_WORD_MACRO_DEFINE     32829
#define ID_SYNTAX_WORD_DEGREE           32830
#define ID_SYNTAX_WORD_HDOB             32831
#define ID_SYNTAX_WORD_START            32832
#define ID_SYNTAX_WORD_FUNCTION         32833
#define ID_SYNTAX_WORD_LABLE            32834
#define ID_SYNTAX_WORD_ADDR             32835
#define ID_SYNTAX_WORD_ARRAY_DEFINE     32836
#define ID_SYNTAX_WORD_ARRAY_MEMBER     32837
#define ID_SYNTAX_WORD_BLOCK_CONNECT    32838
#define ID_SYNTAX_WORD_LINE_CONNECT     32840
#define ID_SYNTAX_WORD_INSN_JOIN        32841
#define ID_OPERATOR_IF                  32842
#define ID_OPERATOR_ELSE                32843
#define ID_OPERATOR_OR                  32844
#define ID_OPERATOR_ALSO                32845
#define ID_OPERATOR_NEG                 32846
#define ID_OPERATOR_CALL                32847
#define ID_OPERATOR_RET                 32849
#define ID_OPERATOR_JMP                 32851
#define ID_OPERATOR_EXIT                32853
#define ID_OPERATOR_BREAK               32854
#define ID_OPERATOR_CONTINUE            32855
#define ID_OPERATOR_INTERRUPT           32856
#define ID_OPERATOR_HLT                 32857
#define ID_OPERATOR_PUSH                32858
#define ID_OPERATOR_POP                 32860
#define ID_OPERATOR_FLAGR               32861
#define ID_OPERATOR_SET                 32862
#define ID_OPERATOR_ENTER               32863
#define ID_OPERATOR_LEAVE               32864
#define ID_OPERATOR_CMP                 32865
#define ID_OPERATOR_XCHG                32866
#define ID_OPERATOR_STRING              32867
#define ID_OPERATOR_WAIT                32868
#define ID_OPERATOR_NOP                 32869
#define ID_OPERATOR_ABOVE               32870
#define ID_OPERATOR_BELOW               32871
#define ID_OPERATOR_GT_ASSIGN           32872
#define ID_OPERATOR_LT_ASSIGN           32873
#define ID_OPERATOR_OVERFLOW            32874
#define ID_OPERATOR_ODD                 32875
#define ID_OPERATOR_ZERO                32876
#define ID_OPERATOR_FWAIT               32877
#define ID_OPERATOR_FNOP                32878
#define ID_OPERATOR_DIVISOR             32879
#define ID_OPERATOR_SQUARE_ROOT         32880
#define ID_OPERATOR_PI                  32881
#define ID_OPERATOR_LOG                 32882
#define ID_OPERATOR_LN                  32883
#define ID_OPERATOR_POWER               32884
#define ID_OPERATOR_MUL                 32887
#define ID_OPERATOR_DIV                 32889
#define ID_OPERATOR_SIGN                32890
#define ID_SYNTAX_WORD_WCHAR            32892
#define ID_SYNTAX_WORD_WSTRING          32893
#define ID_OASM_HELP                    32895
#define ID_CHECK_NEW_VERSION            32900
#define ID_NEW_SOLUTION                 32903
#define ID_NEW_PROJECT                  32904
#define ID_ADD_PROJECT                  32912
#define ID_ADD_FLODER                   32913
#define ID_OPEN_SOLUTION                32916
#define ID_CLOSE_SOLUTION               32920
#define ID_REMOVE_PROJECT               32922
#define ID_REFRESH_PROJECT              32924
#define ID_DELETE_FILE                  32927
#define ID_NEW_IN_PROJECT_FILE          32928
#define ID_RENAME                       32929
#define ID_REFRESH                      32930
#define ID_PROJECT_BUILD                32933
#define ID_OPEN_IN_PROJECT_FILE         32934
#define ID_BUILD_CUR_PROJECT            32935
#define ID_SET_START_PROJECT            32937
#define ID_BUILD_ALL_PROJECT            32939
#define ID_INSERT_REG_AL                32986
#define ID_INSERT_REG_AH                32987
#define ID_INSERT_REG_BL                32988
#define ID_INSERT_REG_BH                32989
#define ID_INSERT_REG_CL                32990
#define ID_INSERT_REG_CH                32991
#define ID_INSERT_REG_DL                32992
#define ID_INSERT_REG_DH                32993
#define ID_INSERT_REG_AX                32994
#define ID_INSERT_REG_BX                32995
#define ID_INSERT_REG_CX                32996
#define ID_INSERT_REG_DX                32997
#define ID_INSERT_REG_BP                32998
#define ID_INSERT_REG_SP                32999
#define ID_INSERT_REG_SI                33000
#define ID_INSERT_REG_DI                33001
#define ID_INSERT_REG_EAX               33002
#define ID_INSERT_REG_EBX               33003
#define ID_INSERT_REG_ECX               33004
#define ID_INSERT_REG_EDX               33005
#define ID_INSERT_REG_EBP               33006
#define ID_INSERT_REG_ESP               33007
#define ID_INSERT_REG_ESI               33008
#define ID_INSERT_REG_EDI               33009
#define ID_INSERT_REG_CS                33010
#define ID_INSERT_REG_DS                33011
#define ID_INSERT_REG_ES                33012
#define ID_INSERT_REG_SS                33013
#define ID_INSERT_REG_FS                33014
#define ID_INSERT_REG_GS                33015
#define ID_INSERT_REG_CR0               33017
#define ID_INSERT_REG_CR2               33018
#define ID_INSERT_REG_CR3               33019
#define ID_INSERT_REG_CR4               33020
#define ID_INSERT_REG_DR0               33021
#define ID_INSERT_REG_DR1               33022
#define ID_INSERT_REG_DR2               33023
#define ID_INSERT_REG_DR3               33024
#define ID_INSERT_REG_DR6               33025
#define ID_INSERT_REG_DR7               33026
#define ID_INSERT_REG_TR0               33027
#define ID_INSERT_REG_TR1               33028
#define ID_INSERT_REG_TR2               33029
#define ID_INSERT_REG_TR3               33030
#define ID_INSERT_REG_TR4               33031
#define ID_INSERT_REG_TR5               33032
#define ID_INSERT_REG_TR6               33033
#define ID_INSERT_REG_TR7               33034
#define ID_INSERT_REG_ST0               33035
#define ID_INSERT_REG_ST1               33036
#define ID_INSERT_REG_ST2               33037
#define ID_INSERT_REG_ST3               33038
#define ID_INSERT_REG_ST4               33039
#define ID_INSERT_REG_ST5               33040
#define ID_INSERT_REG_ST6               33041
#define ID_INSERT_REG_ST7               33042
#define ID_INSERT_REG_MM0               33043
#define ID_INSERT_REG_MM1               33044
#define ID_INSERT_REG_MM2               33045
#define ID_INSERT_REG_MM3               33046
#define ID_INSERT_REG_MM4               33047
#define ID_INSERT_REG_MM5               33048
#define ID_INSERT_REG_MM6               33049
#define ID_INSERT_REG_MM7               33050
#define ID_INSERT_REG_XMM0              33051
#define ID_INSERT_REG_XMM1              33052
#define ID_INSERT_REG_XMM2              33053
#define ID_INSERT_REG_XMM3              33054
#define ID_INSERT_REG_XMM4              33055
#define ID_INSERT_REG_XMM5              33056
#define ID_INSERT_REG_XMM6              33057
#define ID_INSERT_REG_XMM7              33058
#define ID_INCLUDE_OASM_HEAD            33059
#define ID_INCLUDE_CUR_TEXT             33060
#define ID_INCLUDE_SYS_TEXT             33061
#define ID_INCLUDE_CUR_LIB              33062
#define ID_INCLUDE_SYS_LIB              33063
#define ID_INCLUDE_GENERAL              33064
#define ID_SENTENCE_IF                  33065
#define ID_SENTENCE_IF_ELSE             33066
#define ID_SENTENCE_IF_ELSEIF_ELSE      33067
#define ID_SENTENCE_WHILE               33068
#define ID_SENTENCE_FUNCTION            33072
#define ID_SENTENCE_SEGMENT_DATA        33074
#define ID_SENTENCE_SEGMENT_RDATA       33075
#define ID_SENTENCE_SEGMENT_BSS         33076
#define ID_SENTENCE_SEGMENT_CODE        33077
#define ID_SENTENCE_SEGMENT_EXTERN      33078
#define ID_OPEN_CUR_FLODER              33080
#define ID_RESEDITOR                    33082
#define ID_FILE_SAVE_ALL                33084
#define ID_DASM_PE_FILE                 33086
#define ID_Menu33087                    33087
#define ID_SET_BREAK_POINT              33088
#define ID_33091                        33091
#define ID_BEGIN_DEBUGGER               33092
#define ID_33093                        33093
#define ID_STOP_DEBUGGER                33094
#define ID_CLEAR_ALL_BREAK_POINT        33097
#define ID_DEBUG_SINGLE_LINE            33098
#define ID_DEBUG_SINGLE_SENTENCE        33099
#define ID_OPEN_OLAN_WEB                33103
#define ID_OPEN_OLANGUAGE_WEB           33104
#define ID_BUTTON33105                  33105
#define ID_SYNTAX_WORD_SEGMENT_EXTERN   33106
#define ID_33107                        33107
#define ID_33108                        33108
#define ID_33109                        33109
#define ID_HIGH_LIGHT_OASM              33110
#define ID_HIGH_LIGHT_OML               33111
#define ID_OML_INCLUDE_CUR_TEXT         33112
#define ID_OML_INCLUDE_SYS_TEXT         33113
#define ID_OML_INCLUDE_CUR_LIB          33114
#define ID_OML_INCLUDE_SYS_LIB          33115
#define ID_OML_SENTENCE_FUNCTION        33116
#define ID_OML_SENTENCE_IF              33117
#define ID_OML_SENTENCE_IF_ELSE         33118
#define ID_OML_SENTENCE_IF_ELSEIF_ELSE  33119
#define ID_OML_SENTENCE_WHILE           33120
#define ID_33121                        33121
#define ID_OML_HELP                     33122
#define ID_33123                        33123
#define ID_REBUILD_CUR_PROJECT          33124
#define ID_33125                        33125
#define ID_REBUILD_AND_LINK             33126
#define ID_33127                        33127
#define ID_ASSOCIATE_O_FILE             33128
#define ID_GOTO_LINE                    33129
#define ID_TAB_ADD                      33131
#define ID_TAB_SUB                      33132
#define ID_COMMENT_ADD                  33133
#define ID_COMMENT_SUB                  33134
#define ID_COMMONT_ADD                  33135
#define ID_33136                        33136
#define ID_33137                        33137
#define ID_OPEN_FILE_TEMPLATE           33138
#define ID_33139                        33139
#define ID_FAST_INPUT_LIST              33140
#define ID_FILE_TEMPLATE_LIST           33141
#define ID_INDICATOR_LINE               59142
#define ID_INDICATOR_DOC                59143

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        397
#define _APS_NEXT_COMMAND_VALUE         33142
#define _APS_NEXT_CONTROL_VALUE         1053
#define _APS_NEXT_SYMED_VALUE           319
#endif
#endif
