

#ifndef _MESSAGE_H_
#define _MESSAGE_H_

enum DOASM_MESSAGE
{
	DOASM_MSG_NULL,	
	DOASM_MSG_COMMAND_LINE_ERROR,
	DOASM_MSG_PE_FILE_NOT_EXIST,
	DOASM_MSG_PE_FILE_INVALID,
	DOASM_MSG_LOAD_PE_FILE_FAILD,
	DOASM_MSG_LOAD_LANGUAGE_FILE_FAILD,
	DOASM_MSG_OPEN_DOASM_FILE_FAILD,
	DOASM_MSG_DOASM_FILE_INFO,
	DOASM_MSG_SEGMENT_INFO_TITLE,
	DOASM_MSG_SEGMENT_NAME,
	DOASM_MSG_SEGMENT_INFO,
	DOASM_MSG_CODE_SEGMENT,
	DOASM_MSG_NO_EXECUTE_SEGMENT,
	DOASM_MSG_ENTRY_POINT,
	DOASM_MSG_ALL_ZERO_DATA,
	DOASM_MSG_NOT_INSTRUCTION_DATA,
	DOASM_MSG_UNKNOW_INSTRUCTION_DATA,	
	DOASM_MSG_LANGUAGE_INTER_CODE_INVALID,
};

enum DOASM_LANGUAGE_TYPE
{
	DLT_NULL,
	DLT_ENGLISH,
	DLT_SIMPLE_CHINESE,	
};

char* GetDoasmMessageInfo(int nMsgCode);

#endif